baseURL = 'http://attitudeforthecloud.com/'
languageCode = 'en-us'
title = 'Attitude for the Cloud'
theme = 'beautifulhugo'
copyright = 'Copyright 2024-{year} J Kersey Enterprises, LLC. All rights reserved.'

[params]
since = '2024'

[author]
name = 'Jordon Kersey'


[[deployment.targets]]
name = "s3"
URL = "s3://attitudeforthecloud.com?region=us-east-2"
cloudFrontDistributionID = "<cloudFrontDistributionID>"